### ISSUE TITLE
GGG have explicitly called this out as bannable to use.

### ISSUE THREAD

**Issue by RichMoney** [vmv/PoeSmoother#1]
While the intentions of this program may be good, it clearly crosses the line into giving players an advantage through modifying game files and the code could be used maliciously as well to cheat at the game explicitly.

https://www.pathofexile.com/forum/view-thread/1589960/filter-account-type/staff

**Comment by vmv** [comment]
Lol, what are those advantages you talk about ? Faster loading areas, better fps ?!?!? 
Are this advantages ????
Thank you for clarifying this.

**Comment by RichMoney** [comment]
If you can't see how modifying the game files in general *can* be used maliciously, then I'm not going to explain it. 

Your modification may not be *bad*, but it still makes the same type of changes and has now been EXPLICITLY labeled as bannable by GGG. If GGG says that creating new visual settings is bannable, then it's bannable. This isn't a moral debate, I'm simply stating a fact. Given that they have cheat detection and they have the source of your changes because it's posted here, I would stop using it. 

Rich

**Comment by vmv** [comment]
There are much better tools, if anyone wants to cheat....not this.
In the end, it's the user choice to cheat or not.
Anyway, i used to care if i get a ban or not...but not anymore. 
Ban me if you or any GGG team member want.
I am using it.
