### ISSUE TITLE
deleted longest file names but is still not patching micros.

### ISSUE THREAD

**Issue by Soruja** [vmv/PoeSmoother#1]
deleted the 2 longest names and still refuses to patch micro and i searched the entire hard drive for long file names

**Comment by vmv** [comment]
I don't think they are long filenames, but long paths..right ?
Like C:\Users\vmv\Desktop\Art\Models\Effects\arcticbreath....etc (add here whats inside Client.ggpk).
You should use the tool straight from Desktop or anywhere near drive C/D.
If you have the game or the tool far far away in some folders,...this can cause problems.
