### ISSUE TITLE
graph bug

### ISSUE THREAD

**Issue by SilentWarrior1** [vmv/PoeSmoother#3]
there's a weird bug after applying Globe girls : http://www.picshare.ru/view/7422166/
and some gem icons bugging too http://joxi.ru/p27ggYH0kXMV27
used latest version (0.15v also has this glitch)

**Comment by HyperWeapon** [comment]
This is happening to me as well. I mainly use this for the Globe Girls and would appreciate someone fixing this.

**Comment by HyperWeapon** [comment]
Looked into it. Was simple to fix with just some image editing. Replace 2DArt_UIImages_InGame_1.dds in /config/UiChanges/replaceUiFiles/Art/Textures/Interface/2D/ with this one.
http://www.mediafire.com/download/jmb3xkln3age3bx/2DArt_UIImages_InGame_1.dds

**Comment by SilentWarrior1** [comment]
hm... seems they're broken again

**Comment by vmv** [comment]
Yes i know, but i don't maintain this anymore...sorry.
