### ISSUE TITLE
effects and sounds still broken for birds

### ISSUE THREAD

**Issue by Soruja** [vmv/PoeSmoother#9]
i cant catch exactly what is causing it anymore in the sound setting ... something about i think it was swallow fly 3 or something (the game crashes and asks to debug, covering the error so fast and if u try to move the error to the side to read it, the actual error is now a white box so u cant read it)

all i can say is if u take off effects and sounds, it works fine. 

edit: scorhing ray is still affected by removed skills as well. it will pop up two errors and play fine but soon as a person uses scorching ray, ur game will crash

keep in mind please vmv im not at all trying to rush fixes nor trying to repost some. a bugfix list  or a eventually "to do" list would be nice below each of the updates so we can know what has already been mentioned to avoid reposting

**Comment by vmv** [comment]
This is a fast fix for that critter:
[Swallow.zip](https://github.com/vmv/PoeSmoother/files/667545/Swallow.zip)

Extract this into your config/OtherEffects/Metadata/Critters...
Try and see if it's working.

**Comment by Soruja** [comment]
unable to replace 8 files

File count = 8
Unable to replace file Swallow\NestLoops\Fly1.otc -> Missing
Unable to replace file Swallow\NestLoops\Fly2.otc -> Missing
Unable to replace file Swallow\NestLoops\Fly3.otc -> Missing
Unable to replace file Swallow\NestLoops\Fly4.otc -> Missing
Unable to replace file Swallow\NestLoops\FlyRandom.otc -> Missing
Unable to replace file Swallow\ProxyPerch\ProxyPerch1.otc -> Missing
Unable to replace file Swallow\ProxyPerch\ProxyPerch2.otc -> Missing
Unable to replace file Swallow\ProxyPerch\ProxyPerch3.otc -> Missing

extracted the swallow folder to my desktop and then dragged the swallow folder into the poe smoother and said yes replace

**Comment by vmv** [comment]
Move the zip file to your config/OtherEffects...than choose "extract here".
It has both folder with remove/restore.

**Comment by Soruja** [comment]
ok i managed to prnt screen in time to catch the current error. i went to the config folder and completely copy pasted replacing both folders so now it is your current folders you supplied me. 

went to apply remove sound and effects

i enter highgate and

"":resolving metadata/critters/swallow/nestloops/fly3 failed

**Comment by vmv** [comment]
I don't have any errors by not touching this critters.
Restore the files than delete the Swallow folders from both sides.
On Critters should be only 1 file: RoamingCritterBase.otc

**Comment by Soruja** [comment]
still updating the ggpk...

**Comment by Soruja** [comment]
alright ty vmv. with that removed the remove sounds works now.

hope to see more fixes/added options down the road when you have time <3

**Comment by vmv** [comment]
Yep, i will try to keep it up with GGG updates..:)
